# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'Home', url: 'index.html'}
- {name: 'Research', url: '#publications'}
- {name: 'Misc', url: '#misc'}
- {name: 'CV', url: 'cv.pdf'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'envelope', link: 'mailto:tsafavi@umich.edu'}
- {icon: 'graduation-cap', link: 'https://scholar.google.com/citations?user=bIWFjekAAAAJ&hl=en'}
- {icon: 'twitter', link: 'http://www.twitter.com/tararootcake'}
- {icon: 'github', link: 'https://www.github.com/tsafavi'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/tsafavi/'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
