# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-1'

menu:
- {name: 'Home', url: 'index.html'}
- {name: 'News', url: '#news'}
- {name: 'Research', url: '#publications'}
- {name: 'Misc', url: '#misc'}
  # - {name: 'CV', url: 'cv.pdf'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
  - {name: 'Email', icon: 'envelope', link: 'mailto:tsafavi@umich.edu'}
  - {name: 'Google Scholar', icon: 'graduation-cap', link: 'https://scholar.google.com/citations?hl=en&user=bIWFjekAAAAJ&view_op=list_works&sortby=pubdate'}
  - {name: 'Twitter', icon: 'twitter', link: 'http://www.twitter.com/tararootcake'}
  - {name: 'GitHub', icon: 'github', link: 'https://www.github.com/tsafavi'}
  - {name: 'LinkedIn', icon: 'linkedin', link: 'http://www.linkedin.com/in/tsafavi/'}

links:
  email: "mailto:tsafavi@umich.edu"
  linkedin: "http://www.linkedin.com/in/tsafavi/"
  scholar: "https://scholar.google.com/citations?hl=en&user=bIWFjekAAAAJ&view_op=list_works&sortby=pubdate"
  twitter: "https://www.twitter.com/tararootcake"
  github: "https://www.github.com/tsafavi"

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
